- Sources/CSS/Color.swift
> Fixed rendering of rgba lol

- Sources/CSS/Geometry.swift
@amotion needed `height` but added some other missing ones too
> added some missing geometry

- Sources/CSS/Border.swift
- Sources/CSS/Box.swift
- Sources/CSS/Common.swift
- Sources/CSS/Display.swift
- Sources/CSS/Font.swift
- Sources/CSS/List.swift
- Sources/CSS/Size.swift
- Sources/CSS/Text.swift
General cleanup I discovered when looking into alternative ways of representing colors.
> Store values statically

- Sources/ApplicativeRouter/ApplicativeRouter.swift
- Better voiding
- Consistency
> Fixes around routing

- Sources/Css/Background.swift
- Sources/Css/Border.swift
- Sources/Css/Box.swift
- Sources/Css/Display.swift
- Sources/Css/Font.swift
- Sources/Css/Geometry.swift
- Sources/Css/List.swift
- Sources/Css/Stylesheet.swift
- Sources/Css/Text.swift
- Sources/CssReset/Reset.swift
- Sources/HtmlPrettyPrint/Pretty.swift
- Tests/CssTests/BackgroundTests.swift
- Tests/CssTests/BorderTests.swift
- Tests/CssTests/FullStylesheetTests.swift
- Tests/CssTests/MediaTests.swift
- Tests/CssTests/RenderTests.swift
- Tests/CssTests/SizeTests.swift
- Tests/HtmlCssSupportTests/HtmlCssSupportTests.swift
- Tests/HtmlPrettyPrintTests/__Snapshots__/HtmlPrettyPrintTests.testPretty.html
- Tests/HtmlTests/FullDocumentTests.swift
- Tests/HtmlTests/HtmlTests.swift
- Tests/HtmlTests/ViewTests.swift
- Tests/HtmlTests/__Snapshots__/FullDocumentTests.testDocument.html
Also undoing the `Stylesheet` statics. Was seeing bad build times and more type checking ambiguity. Can reinvestigate in the future.
> Remove stylesheet statics

- Sources/Html/Aria.swift
> ARIA attributes

- Package.swift
- README.md
- Sources/ApplicativeRouter/ApplicativeRouter.swift
- Tests/ApplicativeRouterTests/ApplicativeRouterTests.swift
Wraps up body request routing.
> Body by routing

- README.md
- Sources/Html/View.swift
Updating the README with some changes from the last coupla weeks.
> README Updates

- Sources/ApplicativeRouter/ApplicativeRouter.swift
- Tests/ApplicativeRouterTests/ApplicativeRouterTests.swift
> Form data combinators

- Sources/HttpPipeline/Conn.swift
- Sources/HttpPipeline/Middleware.swift
- Sources/HttpPipeline/Response.swift
- Sources/HttpPipelineHtmlSupport/Support.swift
- Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift
interfaces better with various APIs.
> Change response body to Data

- Package.resolved
- Package.swift
Quick bump to the latest Prelude.
> Bump Prelude

- Package.resolved
- Sources/Css/Appearance.swift
- Tests/CssTests/FullStylesheetTests.swift
- Tests/CssTests/__Snapshots__/FullStylesheetTests/testABigStyleSheet.1.css
working with Cornett, gonna merge...
> Appearance

- Sources/Html/Elements.swift
> add meta name

- Sources/Html/Elements.swift
- Sources/MediaType/MediaType.swift
> support for svg

- Package.swift
- Sources/Html/Attributes.swift
- Sources/Html/Elements.swift
Some viewport stuff.
``` swift
meta(viewport: .width(.deviceWidth), .initialScale(1))
// meta(viewport: .width(.deviceWidth) >| [.initialScale(1)])
```
> Viewport meta attributes

- Package.resolved
- Package.swift
- Sources/HttpPipeline/Middleware.swift
- Sources/HttpPipeline/ResponseHeader.swift
- Sources/HttpPipeline/Status.swift
- Sources/HttpPipelineTestSupport/HttpPipelineTestSupport.swift
- Tests/HttpPipelineTests/HttpPipelineTests.swift
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testBasicAuth_Authorized.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testBasicAuth_Unauthorized.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testContentLengthMiddlewareTransformer.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testCookies.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testHtmlResponse.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testPipeline.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testRedirect.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testRedirect_AdditionalHeaders.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testWriteHeaders.1.Conn.txt
Alternative (or supporting?) idea to https://github.com/pointfreeco/swift-web/pull/52.
> Automatically include Content-Length

- README.md
- Sources/HttpPipeline/Middleware.swift
- Web.playground/Contents.swift
- Web.playground/contents.xcplayground
I updated the playgrounds too, and made that fix to `send` that we talked about where it coalesce existing data to `Data()` if necessary. was running into some weird problems without.
> Updated readme and more

- Sources/ApplicativeRouter/Combinators.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
This is why we shouldn't review PR's over margaritas... 
I fixed a dumb bug in the definition of `lit`...
> Fix bug in lit and added test.

- Sources/ApplicativeRouter/Combinators.swift
- Sources/ApplicativeRouter/SomePartialIsos.swift
- Sources/ApplicativeRouter/SyntaxRouter.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/ApplicativeRouterTests/TestRouter.swift
Quick fix to properly model optional query params. more work on this coming soon...
> Fixed some opt/req query params.

- Sources/HttpPipeline/Status.swift
Starting to work on some error handling middleware and needed to support 500 codes. Just adding the rest while I'm in here.
> Add more status codes

- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRequestLogger.1.txt
This wraps middleware to log information about the requests that come through and time the middleware.
> Request logger middleware transformer

- Sources/Css/Background.swift
- Sources/Css/Display.swift
- Sources/Css/Flexbox.swift
- Sources/Css/Render.swift
Needed a few things, will make comments inline!
> Some CSS updates

- Package.resolved
- Package.swift
- Sources/HttpPipeline/ResponseHeader.swift
> Bump Prelude/SnapshotTesting

- Sources/Css/Color.swift
- Sources/Css/Display.swift
- Sources/Css/Font.swift
- Sources/Css/Stylesheet.swift
I moved the bare minimum of `TODO`s over from https://www.github.com/pointfreeco/pointfreeco so that it will build without `@testable imports`.
> Move some todos over.

- Makefile
Quick fix for `make bootstrap`.
> Use "sudo tee" for modulemap installation

- Sources/ApplicativeRouter/SomePartialIsos.swift
- Sources/Css/CssSelector.swift
- Sources/Css/Render.swift
- Sources/Html/Aria.swift
- Sources/Html/Attributes.swift
- Sources/Html/Elements.swift
- Sources/Html/Html.swift
- Sources/HtmlCssSupport/Support.swift
- Sources/HttpPipeline/ResponseHeader.swift
- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
- Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift
A few things we're using in master. I'm sure there's more to add here from other branches, though!
> Bring things in from PointFree

- Sources/UrlFormEncoding/UrlFormDecoder.swift
- Tests/LinuxMain.swift
Just making the strategies we use a bit more honest and documenting them along the way. Wrote these while waiting for food and just committed em now. Will probably merge so I can pin `PointFree` to the latest on my branch!
> URL form decoder tweaks

- Sources/ApplicativeRouter/Combinators.swift
- Sources/ApplicativeRouter/RequestData.swift
- Sources/ApplicativeRouter/SyntaxRouter.swift
- Sources/HttpPipeline/ResponseHeader.swift
- Sources/UrlFormEncoding/UrlFormDecoder.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/ApplicativeRouterTests/TestRouter.swift
- Tests/LinuxMain.swift
This ties our new decoder (#91) to our router. There are a few TODO items for things like pretty printing, but this makes things usable!
> More query things

- Sources/ApplicativeRouter/Combinators.swift
- Sources/ApplicativeRouter/SomePartialIsos.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/ApplicativeRouterTests/TestRouter.swift
Some duplication here that I'd love to clean up, but moving fast and making things.
> More codability around form data

- Sources/ApplicativeRouter/Combinators.swift
- Sources/ApplicativeRouter/SomePartialIsos.swift
- Sources/UrlFormEncoding/UrlFormDecoder.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/ApplicativeRouterTests/TestRouter.swift
- Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
A few things that have come up on my Point-Free branch.
> More Form Data Codable Things

- Sources/ApplicativeRouter/Combinators.swift
- Sources/UrlFormEncoding/UrlFormDecoder.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/ApplicativeRouterTests/TestRouter.swift
- Tests/LinuxMain.swift
- Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
Fixed decoding in #96, but still need this fix for routing.
> Optional codable query params should route

- Sources/Css/Render.swift
- Sources/Css/Size.swift
- Sources/Html/Attributes.swift
- Sources/Html/Elements.swift
- Sources/Html/Html.swift
- Sources/Html/Html4.swift
- Sources/Html/Render.swift
- Sources/HttpPipeline/ResponseHeader.swift
- Sources/HttpPipeline/SignedCookies.swift
- Sources/HttpPipelineTestSupport/HttpPipelineTestSupport.swift
- Sources/MediaType/MediaType.swift
- Tests/HtmlTests/HtmlTests.swift
- Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testCookieOptions.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testCookies.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testHtmlResponse.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/HttpPipelineTests/testWriteHeaders.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testBasicAuth_Authorized.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testBasicAuth_Unauthorized_ProtectedPredicate.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testContentLengthMiddlewareTransformer.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRedirectUnrelatedHosts.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRedirectUnrelatedHosts.2.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRequireHerokuHttps.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRequireHerokuHttps.3.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRequireHttps.1.Conn.txt
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRequireHttps.3.Conn.txt
Don't know if I solved this the right way, but it at least fixed my test!
> Don't render boolean attributes that are false.

- Sources/HttpPipeline/ResponseHeader.swift
> Remove string.from(date:)

- Development.xcconfig
- Makefile
- Package.resolved
- Package.swift
- Sources/ApplicativeRouter/SomePartialIsos.swift
- Sources/ApplicativeRouter/SyntaxRouter.swift
- Sources/Css/Color.swift
- Sources/Html/Elements.swift
- Sources/Html/Render.swift
- Sources/HttpPipeline/Response.swift
- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
- Sources/MediaType/MediaType.swift
I think the biggest offenders are in `PointFree`, but these were getting flagged while I was in there.
> Some expression time fixes

- Development.xcconfig
- Sources/Css/Color.swift
- Sources/Css/Display.swift
- Sources/Css/Size.swift
- Sources/HttpPipeline/SignedCookies.swift
- Tests/CssTests/CssRenderTests.swift
- Tests/CssTests/FullStylesheetTests.swift
- Tests/CssTests/__Snapshots__/FullStylesheetTests/testABigStyleSheet.1.css
We have quite a few todos we need to move over from pointfreeco, but these are what we've needed most recently, and this contains a CSS bug fix.
> Some todos and fixes

- Sources/Html/EncodedString.swift
- Sources/Html/PlainText.swift
- Tests/HtmlTests/PlainTextTests.swift
- Tests/HtmlTests/__Snapshots__/PlainTextTests/testPlainText.1.txt
There's a lot more we can do here, but this is a start!
> Plain Text Improvements

- Package.resolved
- Package.swift
- Sources/ApplicativeRouter/PartialIso.swift
- Sources/ApplicativeRouter/SomePartialIsos.swift
- Sources/Html/Attributes.swift
- Sources/Html/Elements.swift
- Sources/HttpPipeline/Middleware.swift
- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
- Sources/HttpPipeline/SignedCookies.swift
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Tests/LinuxMain.swift
Does what it says in the PR title.
> Bring in more TODOs

- Sources/ApplicativeRouter/SomePartialIsos.swift
- Sources/ApplicativeRouter/SyntaxRouter.swift
> Use better initializer

- Makefile
- Package.resolved
- Package.swift
- Sources/HttpPipeline/NIO.swift
- Sources/HttpPipelineExample/main.swift
This is a proof-of-concept and has some stuff to figure out.
> NIO Support

- Sources/HttpPipeline/NIO.swift
Browsers and whatnot send this stuff so I didn't even think of it! Stripe web hooks, on the other hand...
> Read body bytes regardless of Content-Length

- Dockerfile
- Package.resolved
- Package.swift
- Tests/LinuxMain.swift
- Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testBrackets.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testBracketsWithIndices.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithFormatted.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithIso8601.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithIso8601.2.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithMillisecondsSince1970.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithSecondsSince1970.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDefaultStrategyAccumulatePairs.1.txt
- Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDefaultStrategyAccumulatePairs.2.txt
> Custom snapshot format

- Sources/HttpPipeline/Response.swift
- Sources/UrlFormEncoding/UrlFormDecoder.swift
More fixes for strange linux/ICU quirks! #139
> Change UTC to GMT

- Package.resolved
- Package.swift
- Sources/HttpPipeline/NIO.swift
- Sources/HttpPipeline/SignedCookies.swift
Updating NIO to 1.8.0 and Cryptor to 1.0.4. Big updates, but seems kosher.
> Update some dependencies.

- Sources/HttpPipeline/Conn.swift
- Tests/ApplicativeRouterHttpPipelineSupportTests/ApplicativeRouterHttpPipelineSupportTests.swift
- Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift
- Tests/HttpPipelineTests/HttpPipelineTests.swift
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Tests/HttpPipelineTests/SignedCookieTests.swift
> Add Secure Headers By Default

- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
Not sure why we previously only had to fix this in the app target...
> Swift 4.2 on Linux Fix

- Sources/ApplicativeRouter/SyntaxRouter.swift
> Fix empty query strings

- Package.swift
Quick bump to fix rendering in Point-Free.
> Bump Html to 0.1.3

- Package.swift
- Sources/HtmlPrettyPrint/Pretty.swift
- Tests/HtmlPrettyPrintTests/HtmlPrettyPrintTests.swift
- Tests/HtmlPrettyPrintTests/__Snapshots__/HtmlPrettyPrintTests/testDocument.1.html
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
Bumps to the latest version, fixing stuff along the way.
> Bump SnapshotTesting

- Dockerfile
- Package.swift
- Sources/CssTestSupport/CssTestSupport.swift
- Sources/HtmlTestSupport/HtmlTestSupport.swift
- Sources/HttpPipelineTestSupport/HttpPipelineTestSupport.swift
- Tests/ApplicativeRouterHttpPipelineSupportTests/ApplicativeRouterHttpPipelineSupportTests.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/CssResetTests/CssResetTests.swift
- Tests/CssTests/FlexBoxTests.swift
- Tests/HtmlPlainTextPrintTests/HtmlPlainTextPrintTests.swift
- Tests/HtmlPrettyPrintTests/HtmlPrettyPrintTests.swift
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Tests/HttpPipelineTests/SignedCookieTests.swift
- Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
- Tests/UrlFormEncodingTests/UrlFormEncodingTests.swift
> Bump snapshot testing

- Package.swift
Just wanna get pointfreeco on the newest...
> Update to newest swift-html.

- Sources/HttpPipeline/NIO.swift
Thanks to the help of @weissi, we can now properly run our middleware without it holding up an event loop. Biggest change here is to convert our `IO` to a `Parallel` (which handles does its work on a dispatch queue), and then turn that into an event loop promise.
> Don't block event loop when running middleware.

- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testRequestLogger.1.txt
Trying to track down more problems :/
> Add UUID to request logger.

- Sources/HttpPipeline/SharedMiddlewareTransformers.swift
- Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
> Use UUID function.

- .gitignore
- Sources/HttpPipeline/NIO.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
Looks like there are a couple type-checking regressions around our lens operators and key paths.
> Xcode 11 Support

- Package.swift
- Sources/HtmlCssSupport/Support.swift
- Sources/HtmlPlainTextPrint/HtmlPlainTextPrint.swift
- Tests/HtmlCssSupportTests/HtmlCssSupportTests.swift
- Tests/HtmlPlainTextPrintTests/HtmlPlainTextPrintTests.swift
- Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift
This upgrades the swift-html dependency to be what we just merged into master and fixes a few small things.
> Upgrade HTML dependency

- Sources/ApplicativeRouter/Combinators.swift
- Sources/ApplicativeRouter/RequestData.swift
- Sources/ApplicativeRouter/SyntaxRouter.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
I think we'll need to parse stuff from headers soon and apparently this parser doesn't support it yet...
> Parse headers for requests.

- Makefile
- Package.swift
- README.md
- Sources/Css/Render.swift
- Tests/ApplicativeRouterTests/SyntaxRouterTests.swift
- Tests/ApplicativeRouterTests/TestRouter.swift
Ha this is mainly for us, but "Web" sticks out among our other libs these days.
> Web -> swift-web
