pointfreeco/swift-web

Package.resolved, Package.swift, README.md, Sources/HTML/EncodedString.swift, Sources/HTML/HTML.swift, Sources/HtmlPrettyPrint/Pretty.swift, Tests/HTMLTests/FullDocumentTests.swift, Tests/HTMLTests/HTMLTests.swift, Tests/HTMLTests/ViewTests.swift, Tests/HtmlCssSupportTests/SupportTests.swift, Tests/HtmlPrettyPrintTests/PrettyTests.swift
This adds a whole new package `import HtmlPrettyPrint` that uses @bkase's [DoctorPretty](https://github.com/bkase/DoctorPretty.git) lib to do a prettier render of HTML. It was pretty easy to set up, and will be super useful for tests!
=> Added a pretty printer package

Sources/ApplicativeRouter/ApplicativeRouter.swift, Sources/CSS/Common.swift, Sources/CSS/Display.swift, Sources/HTML/Attributes.swift, Tests/ApplicativeRouterTests/ApplicativeRouterTests.swift
We looked at this a bit but I was based on an older branch. What's the `renderedValue` stuff? Seems to overlap with `render(with key:)`?
=> Some cleanup

Sources/Css/Background.swift, Sources/Css/Border.swift, Sources/Css/Box.swift, Sources/Css/Color.swift, Sources/Css/Display.swift, Sources/Css/Font.swift, Sources/Css/Geometry.swift, Sources/Css/List.swift, Sources/Css/Size.swift, Sources/Css/Text.swift, Sources/CssReset/Reset.swift, Tests/CssTests/BackgroundTests.swift, Tests/CssTests/BorderTests.swift, Tests/CssTests/FullStylesheetTests.swift, Tests/CssTests/MediaTests.swift, Tests/CssTests/RenderTests.swift, Tests/CssTests/SizeTests.swift, Tests/HtmlCssSupportTests/HtmlCssSupportTests.swift, Tests/HtmlTests/FullDocumentTests.swift, Tests/HtmlTests/HtmlTests.swift, Tests/HtmlTests/ViewTests.swift
Big API change but works really nicely for:
- autocomplete
- namespacing (`floatLeft` -> `.left`)
=> Use static members on Stylesheet and Values

README.md, Sources/Html/Attributes.swift, Sources/Html/Elements.swift, Sources/Html/HTML.swift, Sources/HtmlCssSupport/Support.swift, Sources/HtmlPrettyPrint/Pretty.swift, Tests/HtmlTests/FullDocumentTests.swift
This adds compile-time type-checking to node attributes.
``` swift
img([href("spacer.gif")])
// error: type 'Element.Img' does not conform to protocol 'HasHref'
img([src("spacer.gif")])
// compiles file
```
=> Type attributes

Sources/Html/Attributes.swift, Sources/Html/Elements.swift, Sources/Html/Html.swift, Sources/Html/Render.swift, Sources/HtmlCssSupport/Support.swift, Sources/HtmlPrettyPrint/Pretty.swift, Tests/HtmlCssSupportTests/HtmlCssSupportTests.swift, Tests/HtmlPrettyPrintTests/HtmlPrettyPrintTests.swift, Tests/HtmlPrettyPrintTests/__Snapshots__/HtmlPrettyPrintTests.testPretty.html, Tests/HtmlTests/EncodedStringTests.swift, Tests/HtmlTests/FullDocumentTests.swift, Tests/HtmlTests/HtmlTests.swift, Tests/HtmlTests/__Snapshots__/FullDocumentTests.testDocument.html
Certain nodes can only contain certain elements:
- `head` and `body` can only be in `html`
- `link`, `meta`, and `title` can only be in `head`
- `li` can only be in `ol` and `ul`
- `dd` and `dt` can only be in `dl`
And there are more examples.
This PR adds a lightweight typed wrapper around these functions.
``` swift
ul(
[
a([href("/")], ["Home"]),
a([href("/about")], ["About"]),
a([href("/archive")], ["Archive"]),
]
)
// error: cannot convert value of type 'Node' to expected element type
// 'ChildOf<Element.Ul>'
//     a([href("/")], ["Home"]),
//     ^~~~~~~~~~~~~~~~~~~~~~~~
```
=> Typed Child Nodes

README.md, Sources/ApplicativeRouter/ApplicativeRouter.swift, Tests/ApplicativeRouterTests/ApplicativeRouterTests.swift
Indexed generally has `I` and `J` and our parser is only indexed on `I`, so this probably breaks a lot of axioms at the moment. For now unblocking so we can use. Another future option (in lieu of figuring out IxEverything): remove a lil bit of correctness to simplify (_e.g._, let a `GET` parser check for a request body and quietly fail at runtime).
=> Support a kind of IxApply

Sources/Html/Attributes.swift, Sources/Html/Elements.swift, Sources/Html/EncodedString.swift, Sources/Html/Html.swift, Tests/HtmlTests/FullDocumentTests.swift, Tests/HtmlTests/__Snapshots__/FullDocumentTests/testDocument.1.html
This at least limits security vulnerabilities to the user of the lib putting in an unsafe literal string.
=> Use string literals for the content of script and svg tags

Package.swift, Sources/ApplicativeRouterHttpPipelineSupport/ApplicativeRouterHttpPipelineSupport.swift, Tests/ApplicativeRouterHttpPipelineSupportTests/ApplicativeRouterHttpPipelineSupportTests.swift, Tests/ApplicativeRouterHttpPipelineSupportTests/__Snapshots__/ApplicativeRouterHttpPipelineSupportTests/testRoute.1.home.Conn.txt, Tests/ApplicativeRouterHttpPipelineSupportTests/__Snapshots__/ApplicativeRouterHttpPipelineSupportTests/testRoute.2.episode.Conn.txt, Tests/ApplicativeRouterHttpPipelineSupportTests/__Snapshots__/ApplicativeRouterHttpPipelineSupportTests/testRoute.3.unrecognized.Conn.txt, Tests/ApplicativeRouterHttpPipelineSupportTests/__Snapshots__/ApplicativeRouterHttpPipelineSupportTests/testRoute_UnrecognizedWithCustomNotFound.1.unrecognized.Conn.txt
One last piece of middleware transformer I forgot from my last PR #55. This takes a router, some not found middleware, and does the routing.
I added this to a package `ApplicativeRouterHttpPipelineSupport` that depends on each the router and pipeline.
=> Added routing middleware

Sources/HttpPipeline/Conn.swift, Sources/HttpPipeline/Middleware.swift, Sources/HttpPipeline/SharedMiddlewareTransformers.swift, Sources/HttpPipelineHtmlSupport/Support.swift, Tests/ApplicativeRouterHttpPipelineSupportTests/ApplicativeRouterHttpPipelineSupportTests.swift, Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift, Tests/HttpPipelineTests/HttpPipelineTests.swift, Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift, Tests/HttpPipelineTests/SignedCookieTests.swift
We've talked about this IRL, so I wanted to give it a shot. I changed `Middleware<I, J, A, B>` to be functions `(Conn<I, A>) -> IO<Conn<J, B>>` so that all middleware can do side effects in `IO`. This will help with composition in point free since right now we have a weird hodgepodge of middleware that returns pure `Conn`'s and `IO<Conn>`'s.
it does add some complexity tho! so wanna think it through. whatdya think?
=> [Proof of concept] Make middleware go `(Conn) -> IO<Conn>`

Sources/HttpPipeline/SharedMiddlewareTransformers.swift, Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift, Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testBasicAuth_Unauthorized_ProtectedPredicate.1.Conn.txt
In something Im working on I wanna be able to control the basic auth based on a predicate on `A`. so adding it as an optional param. also removed an overload of `basicAuth` that I don't think is important.
=> Parameter to control basic auth from predicarte.

Sources/HttpPipeline/UrlFormEncoding.swift, Tests/HttpPipelineTests/UrlFormEncodingTests.swift, Tests/HttpPipelineTests/__Snapshots__/UrlFormEncodingTests/testEncodingCodable.1.txt, Tests/HttpPipelineTests/__Snapshots__/UrlFormEncodingTests/testEncoding_DeepObject.1.txt, Tests/HttpPipelineTests/__Snapshots__/UrlFormEncodingTests/testEncoding_DoubleArray.1.txt, Tests/HttpPipelineTests/__Snapshots__/UrlFormEncodingTests/testEncoding_Emtpy.1.txt, Tests/HttpPipelineTests/__Snapshots__/UrlFormEncodingTests/testEncoding_RootArray_SimpleObjects.1.txt
Pulled out some functions I wrote in a different branch for doing URL form encoding. I don't really know if this is the right way to do form encoding, but it works for our basic needs for now (which is for submitting data to the Stripe API).
One bummer is that we cannot do the reverse since the encoded data is all stringly typed. I wonder if we could do something like the router to have a parser-printer for form data...
=> URL form encoding

Sources/Css/Render.swift
We can call "count" directly on strings now.
=> Fix Swift 4 Substring warning

Sources/ApplicativeRouter/SomePartialIsos.swift, Sources/ApplicativeRouterHttpPipelineSupport/ApplicativeRouterHttpPipelineSupport.swift, Sources/HttpPipeline/Conn.swift, Sources/HttpPipeline/Middleware.swift, Sources/HttpPipeline/Response.swift, Sources/HttpPipeline/SharedMiddlewareTransformers.swift, Sources/HttpPipeline/SignedCookies.swift, Sources/HttpPipelineHtmlSupport/Support.swift, Sources/HttpPipelineTestSupport/HttpPipelineTestSupport.swift, Tests/ApplicativeRouterHttpPipelineSupportTests/ApplicativeRouterHttpPipelineSupportTests.swift, Tests/ApplicativeRouterHttpPipelineSupportTests/__Snapshots__/ApplicativeRouterHttpPipelineSupportTests/testRoute.3.unrecognized.Conn.txt, Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift, Tests/HttpPipelineTests/HttpPipelineTests.swift, Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift
- Prefer typed guarantees of `String(decoding:as:)` over `String(data:encoding:)`
- Prefer typed guarantees of `Data(string.utf8)` over `string.data(encoding: .utf8)`.
- Rename `Conn<Step, Data>` to `Conn<Step, A>`
- Don't use `Data?` in pipeline: respond with `Conn<ResponseEnded, Data>`, not `Conn<ResponseEnded, Data?>`
I'm not sure if we were depending on a semantic difference with `Data?`, but it seems unnecessary.
=> Improved data handling

Package.resolved, Package.swift, Sources/HttpPipeline/SignedCookies.swift
seems the version of `CommonCrypto` that `BlueCryptor` depended on no longer exists, and so updating `BlueCryptor` to fix that. that also introduced a crash in something. maybe I was using the API incorrectly and they fixed a bug on their end, I dunno
=> Cryptor update

Sources/ApplicativeRouter/SyntaxRouter.swift
This one took awhile to track down! It appears that Linux Foundation has some issues with URLComponents and URLs that contain the same query key twice. Let's avoid URLComponents for now, and have a coupla action items:
1. Change it so our GitHub response code string is optional (to avoid the double query, which is kinda undefined behavior).
2. Get a failing test case over to Apple.
=> Fix another crash around URLComponents/URLQueryItem

Sources/HttpPipelineHtmlSupport/Support.swift, Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift, Tests/HttpPipelineTests/SignedCookieTests.swift
Just updating to always go through our `respond(body:contentType)` helper
=> Better way to do respond(view)

.circleci/config.yml, Makefile, Package.swift, Sources/UrlFormEncoding/UrlFormDecoder.swift, Tests/LinuxMain.swift, Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testBrackets.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testBracketsWithIndices.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithFormatted.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithIso8601.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithIso8601.2.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithMillisecondsSince1970.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDateDecodingWithSecondsSince1970.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDefaultStrategyAccumulatePairs.1.txt, Tests/UrlFormEncodingTests/__Snapshots__/UrlFormDecoderTests/testDefaultStrategyAccumulatePairs.2.txt
Our router has been very naively converting form data and query strings to `[String: String]`, which leads to a lot of extra manual parsing. While form data is typically thought of as a dictionary-like structure, this is a lossy format and key collisions make `[(String, String)]` a more accurate format. Because of this, different frameworks and services have adopted different key and value encodings to accommodate things like arrays and nested structure.
The most agnostic parser may work as follows:
``` swift
parse("xs=1&xs=2") == ["xs": ["1", "2"]] // true
```
Meanwhile, other parsers support bracketed and index-bracketed values:
``` swift
parse("xs[]=1&xs[]=2&roots[][value]=hello&roots[][value]=world")
== ["xs": ["1", "2"], "roots": [["value": "hello"], ["value": "world"]]]
// or, with …
```
=> Add URL Form Decoder for Decodable

Sources/ApplicativeRouter/Combinators.swift, Sources/ApplicativeRouter/RequestData.swift, Sources/ApplicativeRouter/SyntaxRouter.swift, Sources/HttpPipeline/ResponseHeader.swift, Sources/UrlFormEncoding/UrlFormDecoder.swift, Tests/ApplicativeRouterTests/SyntaxRouterTests.swift, Tests/ApplicativeRouterTests/TestRouter.swift, Tests/LinuxMain.swift
Some of the form data query routing inadvertently escaped data twice. This PR corrects that and avoid excess escaping.
=> FIx double-escaped query params

Sources/Html/EncodedString.swift, Tests/HtmlTests/EncodedStringTests.swift
We need an escape hatch to use unescaped strings, so adding this.
The main reason I need this is that we have a `@testable import` in `pointfreeco`, which prevents me from building on linux. I would use this to use a non-breaking hyphen `&#8209;`
=> Add escape hatch to unencoded string.

Sources/UrlFormEncoding/UrlFormDecoder.swift, Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
Surprised we didn't hit this sooner! After setting up Point-Free's profile update endpoint, I was greeted with this:
Looks like we have to translate this manually, as browsers plus-encode space in form data.
=> Transform form data "+" to " "

Sources/ApplicativeRouter/SyntaxRouter.swift
If a router doesn't handle a route, it returns `"/"`, which is a bit of a gotcha. Apps can wrap this function with `url(to:)` and `path(to:)` helpers that handle the `nil` case and are free to call `assertionFailure`s in development.
=> Router.absoluteString(for:) should maybe return nil

Sources/HttpPipeline/Middleware.swift, Sources/HttpPipeline/Response.swift, Sources/HttpPipeline/SharedMiddlewareTransformers.swift
Small commit allowing `redirect` to be passed a status.
Future exploration: our `enum Status` should probably become a `struct`, at which point we could even do something interesting with phantom types like:
``` swift
struct Status<Category> {
let code: Int
// …
public static var ok: Status<Success> { return .init(code: 200) }
// …
public static var found: Status<Redirect> { return .init(code: 302) }
}
func redirect(to: String, status: Status<Redirect> = .found) -> // …
```
This would bleed up into, potentially, an extra generic param on `Conn`, though, which might allow for interesting things! Then again, maybe not worth it! Alternatively we could just assert in `redirect`:
``` swift
assert((300...400).contains(status.code))
```
=> Redirect helper

Package.resolved, Package.swift, Sources/HttpPipeline/SignedCookies.swift, Tests/HttpPipelineTests/EncryptionTests.swift, Tests/HttpPipelineTests/SignedCookieTests.swift, Tests/LinuxMain.swift
[Cryptor](https://github.com/IBM-Swift/BlueCryptor/) has a lot of `fatalError`s, so let's guard against them and just return `nil`.
I've opened an issue here https://github.com/IBM-Swift/BlueCryptor/issues/30 about this.
=> Guard against all fatalErrors in Cryptor

Sources/HttpPipeline/Response.swift
=> Use en_US_POSIX locale for cookie formatting

Package.resolved, Package.swift, Sources/Html/Render.swift
This fixes pretty HTML rendering for `pre` elements, which need to not be prefixed with whitespace since they preserve it.
=> Fix pretty renderer for "pre" elements

Sources/HtmlPrettyPrint/Pretty.swift, Tests/HtmlPrettyPrintTests/HtmlPrettyPrintTests.swift
Currently in the `render` on swift-html we will render the children of void elements if there are some:
https://github.com/pointfreeco/swift-html/blob/630aa9da091be1b1db1d2ce3c83796074808c60e/Sources/Html/Render.swift#L20
I don't know if that was done by design, but I do think it's a necessary escape hatch as I have shown in this issue on pointfreeco:
https://github.com/pointfreeco/pointfreeco/issues/335
All this PR does is port that behavior over to `prettyPrint`.
=> Pretty print void element children.

Sources/HttpPipeline/NIO.swift
It's pretty easy to construct a bad URL that Foundation chokes on, and that causes us to close the NIO channel early. Let's prevent this from happening by redirecting to the base URL.
A longer term fix would be to pass in an entire response that can be used so that we can do a 50X response with a custom view. And even more long term would be to stop using foundation for `URL` and `URLRequest`.
=> Specify a base url to prevent early closes.

Sources/UrlFormEncoding/UrlFormDecoder.swift, Tests/UrlFormEncodingTests/UrlFormDecoderTests.swift
This should allow for `1` to decode as true as well.
=> Bool form decoder fixes

README.md
=> Remove Html module from README

Package.swift
We're on an old version of BlueCryptor that is still on Swift 3.1, which isn't supported by Swift 5.
=> Bump Dependencies

Sources/HttpPipeline/NIO.swift
Fixes #182.
We probably want to add some kind of logging, too.
=> Close Channel on Error

Sources/HttpPipeline/SharedMiddlewareTransformers.swift, Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift, Tests/HttpPipelineTests/__Snapshots__/SharedMiddlewareTransformersTests/testBasicAuth_Authorized_LowercasedHeaderName.1.Conn.txt, Tests/LinuxMain.swift
sometimes authorization header on Linux is typed lowercased which cause basic authorization fails, this simple fix patch the problem
=> allow basic auth even if header is lowercased

.github/workflows/ci.yml, Makefile, Package.resolved, Package.swift, Sources/HttpPipeline/NIO.swift, Tests/ApplicativeRouterHttpPipelineSupportTests/ApplicativeRouterHttpPipelineSupportTests.swift, Tests/HttpPipelineHtmlSupportTests/HttpPipelineHtmlSupportTests.swift, Tests/HttpPipelineTests/HttpPipelineTests.swift, Tests/HttpPipelineTests/SharedMiddlewareTransformersTests.swift, Tests/HttpPipelineTests/SignedCookieTests.swift
This PR updates swift-web to interact with `IO` in an asynchronous way. Surprisingly, only tests were calling `perform` directly, and `Parallel.run` is now async-safe on the `async` branch.
=> Async-Await
